# Generated by Django 3.0.3 on 2020-02-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_file', models.FileField(null=True, upload_to='images', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('cost_of_production', models.FloatField(null=True)),
                ('selling_net_price', models.FloatField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
