# Generated by Django 3.0.3 on 2020-02-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='wedding_products.Image'),
        ),
    ]
