# Generated by Django 3.0.3 on 2020-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0008_auto_20200216_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('szt', 'sztuki'), ('mm', 'milimetry'), ('m', 'mmetry')], default='szt', max_length=3),
        ),
    ]
