# Generated by Django 3.0.3 on 2020-02-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0009_auto_20200217_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('szt.', 'sztuki'), ('mm', 'milimetry'), ('m', 'metry')], default='szt.', max_length=4),
        ),
    ]
