# Generated by Django 3.0.3 on 2020-02-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0011_product_selling_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategoria produktu', null=True, on_delete=django.db.models.deletion.PROTECT, to='wedding_products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_of_production',
            field=models.FloatField(blank=True, help_text='Koszt', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Opis', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, help_text='Nazwa produktu', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Ilość', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_final_price',
            field=models.FloatField(blank=True, help_text='Cena sprzedaży brutto', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_net_price',
            field=models.FloatField(blank=True, help_text='Cena sprzedaży netto', null=True),
        ),
    ]
