# Generated by Django 3.0.3 on 2020-02-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0014_auto_20200217_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_final_price',
        ),
    ]
