# Generated by Django 3.0.3 on 2020-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0015_remove_product_selling_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
