# Generated by Django 3.0.3 on 2020-02-27 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0019_auto_20200226_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When the visit was created'),
        ),
    ]
