# Generated by Django 3.0.3 on 2020-02-27 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0020_auto_20200227_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
