# Generated by Django 3.0.3 on 2020-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0022_auto_20200227_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
        migrations.AddField(
            model_name='visit',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='visit',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
