# Generated by Django 3.0.3 on 2020-03-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_products', '0024_auto_20200303_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wedding_products.Visit'),
        ),
    ]
